version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
    target-branch: main
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
    target-branch: main
    allow:
      - dependency-type: direct
      - dependency-type: indirect
