version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: postgres
      DB_USERNAME: postgres
    command: ["make", "test-coverage", "analyse", "lint"]

  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
