version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: ["make", "start-app"]
    depends_on:
      - db
    container_name: task-manager-app

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www
    ports:
        - "5173:5173"
    command: ["make", "start-frontend"]
    depends_on:
      - app
    container_name: task-manager-web

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54320:5432"
    volumes:
      - task-manager-pgdata:/var/lib/postgresql/data
    container_name: task-manager-db

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  task-manager-pgdata:
