version: '3.7'

services:
  application:
    build: .
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: ["make", "start-app"]

  frontend:
    build: .
    volumes:
      - .:/app:delegated
    command: ["make", "start-frontend"]
    depends_on:
      - application

  database:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - task-manager-pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  task-manager-pgdata:
