name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    strategy:
      matrix:
        php-versions: ['8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.2

      - name: Setup project
        run: make setup

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test-coverage

      - name: Run CI
        run: |
          make ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/clover.xml

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t task-manager .
      - name: Tags
        run: |
          docker tag task-manager ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}
          docker tag task-manager ${{ secrets.DOCKER_USERNAME }}/task-manager:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest
